on: 
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]
  jobs:
    build:
      runs-on: host-eduin
      steps:
      - build: actions/checkout@v3
      - name: compile
        run: mvn clean install
Footer
© 2022 GitHub, Inc.
Footer navigation
Terms

